# Ref: https://hub.docker.com/_/mysql
version: '3.1'

services:

  db:
    image: mysql
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    volumes:
      - ./data/enron-mysqldum_v5.sql/:/docker-entrypoint-initdb.d/enron-mysqldum_v5.sql/
      # Populate the database with the provided data